name: 'Custom Action'
description: 'Greeting the input name'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'
runs:
  using: 'node12'
  main: '../../customAction.js'  # Ensure this points to your JavaScript file
