name: 'Hello World JS Action'
description: 'Greet someone and record the time'
runs:
  using: 'node16'
  main: 'index.js'

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
    
outputs:
  time:
    description: 'The time we greeted you'
